//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SecurityGroup_Company", "Companies", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XERP.Server.DAL.LogInDAL.Company), "SecurityGroups", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.LogInDAL.SecurityGroup), true)]
[assembly: EdmRelationshipAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_Company", "Companies", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XERP.Server.DAL.LogInDAL.Company), "SystemUserSecurities", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.LogInDAL.SystemUserSecurity), true)]
[assembly: EdmRelationshipAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_SecurityGroup", "SecurityGroups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XERP.Server.DAL.LogInDAL.SecurityGroup), "SystemUserSecurities", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.LogInDAL.SystemUserSecurity), true)]
[assembly: EdmRelationshipAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SystemUser_SystemUserCode", "SystemUserCodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(XERP.Server.DAL.LogInDAL.SystemUserCode), "SystemUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.LogInDAL.SystemUser), true)]
[assembly: EdmRelationshipAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SystemUser_SystemUserType", "SystemUserTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(XERP.Server.DAL.LogInDAL.SystemUserType), "SystemUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.LogInDAL.SystemUser), true)]
[assembly: EdmRelationshipAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_SystemUser", "SystemUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XERP.Server.DAL.LogInDAL.SystemUser), "SystemUserSecurities", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.LogInDAL.SystemUserSecurity), true)]

#endregion

namespace XERP.Server.DAL.LogInDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LogInEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LogInEntities object using the connection string found in the 'LogInEntities' section of the application configuration file.
        /// </summary>
        public LogInEntities() : base("name=LogInEntities", "LogInEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LogInEntities object.
        /// </summary>
        public LogInEntities(string connectionString) : base(connectionString, "LogInEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LogInEntities object.
        /// </summary>
        public LogInEntities(EntityConnection connection) : base(connection, "LogInEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company> Companies
        {
            get
            {
                if ((_Companies == null))
                {
                    _Companies = base.CreateObjectSet<Company>("Companies");
                }
                return _Companies;
            }
        }
        private ObjectSet<Company> _Companies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecurityGroup> SecurityGroups
        {
            get
            {
                if ((_SecurityGroups == null))
                {
                    _SecurityGroups = base.CreateObjectSet<SecurityGroup>("SecurityGroups");
                }
                return _SecurityGroups;
            }
        }
        private ObjectSet<SecurityGroup> _SecurityGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SystemUserCode> SystemUserCodes
        {
            get
            {
                if ((_SystemUserCodes == null))
                {
                    _SystemUserCodes = base.CreateObjectSet<SystemUserCode>("SystemUserCodes");
                }
                return _SystemUserCodes;
            }
        }
        private ObjectSet<SystemUserCode> _SystemUserCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SystemUser> SystemUsers
        {
            get
            {
                if ((_SystemUsers == null))
                {
                    _SystemUsers = base.CreateObjectSet<SystemUser>("SystemUsers");
                }
                return _SystemUsers;
            }
        }
        private ObjectSet<SystemUser> _SystemUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SystemUserSecurity> SystemUserSecurities
        {
            get
            {
                if ((_SystemUserSecurities == null))
                {
                    _SystemUserSecurities = base.CreateObjectSet<SystemUserSecurity>("SystemUserSecurities");
                }
                return _SystemUserSecurities;
            }
        }
        private ObjectSet<SystemUserSecurity> _SystemUserSecurities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SystemUserType> SystemUserTypes
        {
            get
            {
                if ((_SystemUserTypes == null))
                {
                    _SystemUserTypes = base.CreateObjectSet<SystemUserType>("SystemUserTypes");
                }
                return _SystemUserTypes;
            }
        }
        private ObjectSet<SystemUserType> _SystemUserTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Temp> Temps
        {
            get
            {
                if ((_Temps == null))
                {
                    _Temps = base.CreateObjectSet<Temp>("Temps");
                }
                return _Temps;
            }
        }
        private ObjectSet<Temp> _Temps;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Companies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecurityGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecurityGroups(SecurityGroup securityGroup)
        {
            base.AddObject("SecurityGroups", securityGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SystemUserCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSystemUserCodes(SystemUserCode systemUserCode)
        {
            base.AddObject("SystemUserCodes", systemUserCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SystemUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSystemUsers(SystemUser systemUser)
        {
            base.AddObject("SystemUsers", systemUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SystemUserSecurities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSystemUserSecurities(SystemUserSecurity systemUserSecurity)
        {
            base.AddObject("SystemUserSecurities", systemUserSecurity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SystemUserTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSystemUserTypes(SystemUserType systemUserType)
        {
            base.AddObject("SystemUserTypes", systemUserType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Temps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemps(Temp temp)
        {
            base.AddObject("Temps", temp);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP.LogIn.DAL.LogInDAL", Name="Company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static Company CreateCompany(global::System.String companyID, global::System.Int64 autoID)
        {
            Company company = new Company();
            company.CompanyID = companyID;
            company.AutoID = autoID;
            return company;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                if (_CompanyID != value)
                {
                    OnCompanyIDChanging(value);
                    ReportPropertyChanging("CompanyID");
                    _CompanyID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyID");
                    OnCompanyIDChanged();
                }
            }
        }
        private global::System.String _CompanyID;
        partial void OnCompanyIDChanging(global::System.String value);
        partial void OnCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyTypeID
        {
            get
            {
                return _CompanyTypeID;
            }
            set
            {
                OnCompanyTypeIDChanging(value);
                ReportPropertyChanging("CompanyTypeID");
                _CompanyTypeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyTypeID");
                OnCompanyTypeIDChanged();
            }
        }
        private global::System.String _CompanyTypeID;
        partial void OnCompanyTypeIDChanging(global::System.String value);
        partial void OnCompanyTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyCodeID
        {
            get
            {
                return _CompanyCodeID;
            }
            set
            {
                OnCompanyCodeIDChanging(value);
                ReportPropertyChanging("CompanyCodeID");
                _CompanyCodeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyCodeID");
                OnCompanyCodeIDChanged();
            }
        }
        private global::System.String _CompanyCodeID;
        partial void OnCompanyCodeIDChanging(global::System.String value);
        partial void OnCompanyCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateTaxCode
        {
            get
            {
                return _StateTaxCode;
            }
            set
            {
                OnStateTaxCodeChanging(value);
                ReportPropertyChanging("StateTaxCode");
                _StateTaxCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateTaxCode");
                OnStateTaxCodeChanged();
            }
        }
        private global::System.String _StateTaxCode;
        partial void OnStateTaxCodeChanging(global::System.String value);
        partial void OnStateTaxCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaxRegionCode
        {
            get
            {
                return _TaxRegionCode;
            }
            set
            {
                OnTaxRegionCodeChanging(value);
                ReportPropertyChanging("TaxRegionCode");
                _TaxRegionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaxRegionCode");
                OnTaxRegionCodeChanged();
            }
        }
        private global::System.String _TaxRegionCode;
        partial void OnTaxRegionCodeChanging(global::System.String value);
        partial void OnTaxRegionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CurrentFiscalYear
        {
            get
            {
                return _CurrentFiscalYear;
            }
            set
            {
                OnCurrentFiscalYearChanging(value);
                ReportPropertyChanging("CurrentFiscalYear");
                _CurrentFiscalYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentFiscalYear");
                OnCurrentFiscalYearChanged();
            }
        }
        private Nullable<global::System.Int32> _CurrentFiscalYear;
        partial void OnCurrentFiscalYearChanging(Nullable<global::System.Int32> value);
        partial void OnCurrentFiscalYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultExecutablePath
        {
            get
            {
                return _DefaultExecutablePath;
            }
            set
            {
                OnDefaultExecutablePathChanging(value);
                ReportPropertyChanging("DefaultExecutablePath");
                _DefaultExecutablePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultExecutablePath");
                OnDefaultExecutablePathChanged();
            }
        }
        private global::System.String _DefaultExecutablePath;
        partial void OnDefaultExecutablePathChanging(global::System.String value);
        partial void OnDefaultExecutablePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address3
        {
            get
            {
                return _Address3;
            }
            set
            {
                OnAddress3Changing(value);
                ReportPropertyChanging("Address3");
                _Address3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address3");
                OnAddress3Changed();
            }
        }
        private global::System.String _Address3;
        partial void OnAddress3Changing(global::System.String value);
        partial void OnAddress3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNum
        {
            get
            {
                return _PhoneNum;
            }
            set
            {
                OnPhoneNumChanging(value);
                ReportPropertyChanging("PhoneNum");
                _PhoneNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNum");
                OnPhoneNumChanged();
            }
        }
        private global::System.String _PhoneNum;
        partial void OnPhoneNumChanging(global::System.String value);
        partial void OnPhoneNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNum2
        {
            get
            {
                return _PhoneNum2;
            }
            set
            {
                OnPhoneNum2Changing(value);
                ReportPropertyChanging("PhoneNum2");
                _PhoneNum2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNum2");
                OnPhoneNum2Changed();
            }
        }
        private global::System.String _PhoneNum2;
        partial void OnPhoneNum2Changing(global::System.String value);
        partial void OnPhoneNum2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FaxNum
        {
            get
            {
                return _FaxNum;
            }
            set
            {
                OnFaxNumChanging(value);
                ReportPropertyChanging("FaxNum");
                _FaxNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FaxNum");
                OnFaxNumChanged();
            }
        }
        private global::System.String _FaxNum;
        partial void OnFaxNumChanging(global::System.String value);
        partial void OnFaxNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email2
        {
            get
            {
                return _Email2;
            }
            set
            {
                OnEmail2Changing(value);
                ReportPropertyChanging("Email2");
                _Email2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email2");
                OnEmail2Changed();
            }
        }
        private global::System.String _Email2;
        partial void OnEmail2Changing(global::System.String value);
        partial void OnEmail2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SecurityGroup_Company", "SecurityGroups")]
        public EntityCollection<SecurityGroup> SecurityGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SecurityGroup>("XERP.LogIn.DAL.LogInDAL.FK_SecurityGroup_Company", "SecurityGroups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SecurityGroup>("XERP.LogIn.DAL.LogInDAL.FK_SecurityGroup_Company", "SecurityGroups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_Company", "SystemUserSecurities")]
        public EntityCollection<SystemUserSecurity> SystemUserSecurities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SystemUserSecurity>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_Company", "SystemUserSecurities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SystemUserSecurity>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_Company", "SystemUserSecurities", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP.LogIn.DAL.LogInDAL", Name="SecurityGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecurityGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecurityGroup object.
        /// </summary>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        /// <param name="securityGroupID">Initial value of the SecurityGroupID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static SecurityGroup CreateSecurityGroup(global::System.String companyID, global::System.String securityGroupID, global::System.Int64 autoID)
        {
            SecurityGroup securityGroup = new SecurityGroup();
            securityGroup.CompanyID = companyID;
            securityGroup.SecurityGroupID = securityGroupID;
            securityGroup.AutoID = autoID;
            return securityGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                if (_CompanyID != value)
                {
                    OnCompanyIDChanging(value);
                    ReportPropertyChanging("CompanyID");
                    _CompanyID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyID");
                    OnCompanyIDChanged();
                }
            }
        }
        private global::System.String _CompanyID;
        partial void OnCompanyIDChanging(global::System.String value);
        partial void OnCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecurityGroupID
        {
            get
            {
                return _SecurityGroupID;
            }
            set
            {
                if (_SecurityGroupID != value)
                {
                    OnSecurityGroupIDChanging(value);
                    ReportPropertyChanging("SecurityGroupID");
                    _SecurityGroupID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SecurityGroupID");
                    OnSecurityGroupIDChanged();
                }
            }
        }
        private global::System.String _SecurityGroupID;
        partial void OnSecurityGroupIDChanging(global::System.String value);
        partial void OnSecurityGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecurityGroupTypeID
        {
            get
            {
                return _SecurityGroupTypeID;
            }
            set
            {
                OnSecurityGroupTypeIDChanging(value);
                ReportPropertyChanging("SecurityGroupTypeID");
                _SecurityGroupTypeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecurityGroupTypeID");
                OnSecurityGroupTypeIDChanged();
            }
        }
        private global::System.String _SecurityGroupTypeID;
        partial void OnSecurityGroupTypeIDChanging(global::System.String value);
        partial void OnSecurityGroupTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecurityGroupCodeID
        {
            get
            {
                return _SecurityGroupCodeID;
            }
            set
            {
                OnSecurityGroupCodeIDChanging(value);
                ReportPropertyChanging("SecurityGroupCodeID");
                _SecurityGroupCodeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecurityGroupCodeID");
                OnSecurityGroupCodeIDChanged();
            }
        }
        private global::System.String _SecurityGroupCodeID;
        partial void OnSecurityGroupCodeIDChanging(global::System.String value);
        partial void OnSecurityGroupCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SecurityGroup_Company", "Companies")]
        public Company Company
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.LogIn.DAL.LogInDAL.FK_SecurityGroup_Company", "Companies").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.LogIn.DAL.LogInDAL.FK_SecurityGroup_Company", "Companies").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Company> CompanyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.LogIn.DAL.LogInDAL.FK_SecurityGroup_Company", "Companies");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Company>("XERP.LogIn.DAL.LogInDAL.FK_SecurityGroup_Company", "Companies", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_SecurityGroup", "SystemUserSecurities")]
        public EntityCollection<SystemUserSecurity> SystemUserSecurities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SystemUserSecurity>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SecurityGroup", "SystemUserSecurities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SystemUserSecurity>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SecurityGroup", "SystemUserSecurities", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP.LogIn.DAL.LogInDAL", Name="SystemUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SystemUser object.
        /// </summary>
        /// <param name="systemUserID">Initial value of the SystemUserID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static SystemUser CreateSystemUser(global::System.String systemUserID, global::System.Int64 autoID)
        {
            SystemUser systemUser = new SystemUser();
            systemUser.SystemUserID = systemUserID;
            systemUser.AutoID = autoID;
            return systemUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                if (_SystemUserID != value)
                {
                    OnSystemUserIDChanging(value);
                    ReportPropertyChanging("SystemUserID");
                    _SystemUserID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SystemUserID");
                    OnSystemUserIDChanged();
                }
            }
        }
        private global::System.String _SystemUserID;
        partial void OnSystemUserIDChanging(global::System.String value);
        partial void OnSystemUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SystemUserTypeID
        {
            get
            {
                return _SystemUserTypeID;
            }
            set
            {
                OnSystemUserTypeIDChanging(value);
                ReportPropertyChanging("SystemUserTypeID");
                _SystemUserTypeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SystemUserTypeID");
                OnSystemUserTypeIDChanged();
            }
        }
        private global::System.String _SystemUserTypeID;
        partial void OnSystemUserTypeIDChanging(global::System.String value);
        partial void OnSystemUserTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SystemUserCodeID
        {
            get
            {
                return _SystemUserCodeID;
            }
            set
            {
                OnSystemUserCodeIDChanging(value);
                ReportPropertyChanging("SystemUserCodeID");
                _SystemUserCodeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SystemUserCodeID");
                OnSystemUserCodeIDChanged();
            }
        }
        private global::System.String _SystemUserCodeID;
        partial void OnSystemUserCodeIDChanging(global::System.String value);
        partial void OnSystemUserCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PasswordExpired
        {
            get
            {
                return _PasswordExpired;
            }
            set
            {
                OnPasswordExpiredChanging(value);
                ReportPropertyChanging("PasswordExpired");
                _PasswordExpired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordExpired");
                OnPasswordExpiredChanged();
            }
        }
        private Nullable<global::System.Boolean> _PasswordExpired;
        partial void OnPasswordExpiredChanging(Nullable<global::System.Boolean> value);
        partial void OnPasswordExpiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PasswordExpiresOn
        {
            get
            {
                return _PasswordExpiresOn;
            }
            set
            {
                OnPasswordExpiresOnChanging(value);
                ReportPropertyChanging("PasswordExpiresOn");
                _PasswordExpiresOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordExpiresOn");
                OnPasswordExpiresOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _PasswordExpiresOn;
        partial void OnPasswordExpiresOnChanging(Nullable<global::System.DateTime> value);
        partial void OnPasswordExpiresOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SystemManager
        {
            get
            {
                return _SystemManager;
            }
            set
            {
                OnSystemManagerChanging(value);
                ReportPropertyChanging("SystemManager");
                _SystemManager = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SystemManager");
                OnSystemManagerChanged();
            }
        }
        private Nullable<global::System.Boolean> _SystemManager;
        partial void OnSystemManagerChanging(Nullable<global::System.Boolean> value);
        partial void OnSystemManagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultCompanyID
        {
            get
            {
                return _DefaultCompanyID;
            }
            set
            {
                OnDefaultCompanyIDChanging(value);
                ReportPropertyChanging("DefaultCompanyID");
                _DefaultCompanyID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultCompanyID");
                OnDefaultCompanyIDChanged();
            }
        }
        private global::System.String _DefaultCompanyID;
        partial void OnDefaultCompanyIDChanging(global::System.String value);
        partial void OnDefaultCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultPlantID
        {
            get
            {
                return _DefaultPlantID;
            }
            set
            {
                OnDefaultPlantIDChanging(value);
                ReportPropertyChanging("DefaultPlantID");
                _DefaultPlantID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultPlantID");
                OnDefaultPlantIDChanged();
            }
        }
        private global::System.String _DefaultPlantID;
        partial void OnDefaultPlantIDChanging(global::System.String value);
        partial void OnDefaultPlantIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressID
        {
            get
            {
                return _AddressID;
            }
            set
            {
                OnAddressIDChanging(value);
                ReportPropertyChanging("AddressID");
                _AddressID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddressID");
                OnAddressIDChanged();
            }
        }
        private global::System.String _AddressID;
        partial void OnAddressIDChanging(global::System.String value);
        partial void OnAddressIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ImageID
        {
            get
            {
                return StructuralObject.GetValidValue(_ImageID);
            }
            set
            {
                OnImageIDChanging(value);
                ReportPropertyChanging("ImageID");
                _ImageID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageID");
                OnImageIDChanged();
            }
        }
        private global::System.Byte[] _ImageID;
        partial void OnImageIDChanging(global::System.Byte[] value);
        partial void OnImageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SystemUser_SystemUserCode", "SystemUserCodes")]
        public SystemUserCode SystemUserCode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUserCode>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserCode", "SystemUserCodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUserCode>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserCode", "SystemUserCodes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SystemUserCode> SystemUserCodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUserCode>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserCode", "SystemUserCodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SystemUserCode>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserCode", "SystemUserCodes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SystemUser_SystemUserType", "SystemUserTypes")]
        public SystemUserType SystemUserType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUserType>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserType", "SystemUserTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUserType>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserType", "SystemUserTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SystemUserType> SystemUserTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUserType>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserType", "SystemUserTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SystemUserType>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserType", "SystemUserTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_SystemUser", "SystemUserSecurities")]
        public EntityCollection<SystemUserSecurity> SystemUserSecurities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SystemUserSecurity>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SystemUser", "SystemUserSecurities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SystemUserSecurity>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SystemUser", "SystemUserSecurities", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP.LogIn.DAL.LogInDAL", Name="SystemUserCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemUserCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SystemUserCode object.
        /// </summary>
        /// <param name="systemUserCodeID">Initial value of the SystemUserCodeID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static SystemUserCode CreateSystemUserCode(global::System.String systemUserCodeID, global::System.Int64 autoID)
        {
            SystemUserCode systemUserCode = new SystemUserCode();
            systemUserCode.SystemUserCodeID = systemUserCodeID;
            systemUserCode.AutoID = autoID;
            return systemUserCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SystemUserCodeID
        {
            get
            {
                return _SystemUserCodeID;
            }
            set
            {
                if (_SystemUserCodeID != value)
                {
                    OnSystemUserCodeIDChanging(value);
                    ReportPropertyChanging("SystemUserCodeID");
                    _SystemUserCodeID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SystemUserCodeID");
                    OnSystemUserCodeIDChanged();
                }
            }
        }
        private global::System.String _SystemUserCodeID;
        partial void OnSystemUserCodeIDChanging(global::System.String value);
        partial void OnSystemUserCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SystemUser_SystemUserCode", "SystemUsers")]
        public EntityCollection<SystemUser> SystemUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SystemUser>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserCode", "SystemUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SystemUser>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserCode", "SystemUsers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP.LogIn.DAL.LogInDAL", Name="SystemUserSecurity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemUserSecurity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SystemUserSecurity object.
        /// </summary>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        /// <param name="systemUserID">Initial value of the SystemUserID property.</param>
        /// <param name="securityGroupID">Initial value of the SecurityGroupID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static SystemUserSecurity CreateSystemUserSecurity(global::System.String companyID, global::System.String systemUserID, global::System.String securityGroupID, global::System.Int64 autoID)
        {
            SystemUserSecurity systemUserSecurity = new SystemUserSecurity();
            systemUserSecurity.CompanyID = companyID;
            systemUserSecurity.SystemUserID = systemUserID;
            systemUserSecurity.SecurityGroupID = securityGroupID;
            systemUserSecurity.AutoID = autoID;
            return systemUserSecurity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                if (_CompanyID != value)
                {
                    OnCompanyIDChanging(value);
                    ReportPropertyChanging("CompanyID");
                    _CompanyID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyID");
                    OnCompanyIDChanged();
                }
            }
        }
        private global::System.String _CompanyID;
        partial void OnCompanyIDChanging(global::System.String value);
        partial void OnCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SystemUserID
        {
            get
            {
                return _SystemUserID;
            }
            set
            {
                if (_SystemUserID != value)
                {
                    OnSystemUserIDChanging(value);
                    ReportPropertyChanging("SystemUserID");
                    _SystemUserID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SystemUserID");
                    OnSystemUserIDChanged();
                }
            }
        }
        private global::System.String _SystemUserID;
        partial void OnSystemUserIDChanging(global::System.String value);
        partial void OnSystemUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SecurityGroupID
        {
            get
            {
                return _SecurityGroupID;
            }
            set
            {
                if (_SecurityGroupID != value)
                {
                    OnSecurityGroupIDChanging(value);
                    ReportPropertyChanging("SecurityGroupID");
                    _SecurityGroupID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SecurityGroupID");
                    OnSecurityGroupIDChanged();
                }
            }
        }
        private global::System.String _SecurityGroupID;
        partial void OnSecurityGroupIDChanging(global::System.String value);
        partial void OnSecurityGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_Company", "Companies")]
        public Company Company
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_Company", "Companies").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_Company", "Companies").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Company> CompanyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_Company", "Companies");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Company>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_Company", "Companies", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_SecurityGroup", "SecurityGroups")]
        public SecurityGroup SecurityGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecurityGroup>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SecurityGroup", "SecurityGroups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecurityGroup>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SecurityGroup", "SecurityGroups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SecurityGroup> SecurityGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecurityGroup>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SecurityGroup", "SecurityGroups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SecurityGroup>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SecurityGroup", "SecurityGroups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_UserSecurity_SystemUser", "SystemUsers")]
        public SystemUser SystemUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUser>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SystemUser", "SystemUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUser>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SystemUser", "SystemUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SystemUser> SystemUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SystemUser>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SystemUser", "SystemUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SystemUser>("XERP.LogIn.DAL.LogInDAL.FK_UserSecurity_SystemUser", "SystemUsers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP.LogIn.DAL.LogInDAL", Name="SystemUserType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemUserType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SystemUserType object.
        /// </summary>
        /// <param name="systemUserTypeID">Initial value of the SystemUserTypeID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static SystemUserType CreateSystemUserType(global::System.String systemUserTypeID, global::System.Int64 autoID)
        {
            SystemUserType systemUserType = new SystemUserType();
            systemUserType.SystemUserTypeID = systemUserTypeID;
            systemUserType.AutoID = autoID;
            return systemUserType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SystemUserTypeID
        {
            get
            {
                return _SystemUserTypeID;
            }
            set
            {
                if (_SystemUserTypeID != value)
                {
                    OnSystemUserTypeIDChanging(value);
                    ReportPropertyChanging("SystemUserTypeID");
                    _SystemUserTypeID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SystemUserTypeID");
                    OnSystemUserTypeIDChanged();
                }
            }
        }
        private global::System.String _SystemUserTypeID;
        partial void OnSystemUserTypeIDChanging(global::System.String value);
        partial void OnSystemUserTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP.LogIn.DAL.LogInDAL", "FK_SystemUser_SystemUserType", "SystemUsers")]
        public EntityCollection<SystemUser> SystemUsers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SystemUser>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserType", "SystemUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SystemUser>("XERP.LogIn.DAL.LogInDAL.FK_SystemUser_SystemUserType", "SystemUsers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP.LogIn.DAL.LogInDAL", Name="Temp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Temp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Temp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Temp CreateTemp(global::System.Int64 id)
        {
            Temp temp = new Temp();
            temp.ID = id;
            return temp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Bool_1
        {
            get
            {
                return _Bool_1;
            }
            set
            {
                OnBool_1Changing(value);
                ReportPropertyChanging("Bool_1");
                _Bool_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bool_1");
                OnBool_1Changed();
            }
        }
        private Nullable<global::System.Boolean> _Bool_1;
        partial void OnBool_1Changing(Nullable<global::System.Boolean> value);
        partial void OnBool_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortChar_1
        {
            get
            {
                return _ShortChar_1;
            }
            set
            {
                OnShortChar_1Changing(value);
                ReportPropertyChanging("ShortChar_1");
                _ShortChar_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortChar_1");
                OnShortChar_1Changed();
            }
        }
        private global::System.String _ShortChar_1;
        partial void OnShortChar_1Changing(global::System.String value);
        partial void OnShortChar_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Int_1
        {
            get
            {
                return _Int_1;
            }
            set
            {
                OnInt_1Changing(value);
                ReportPropertyChanging("Int_1");
                _Int_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Int_1");
                OnInt_1Changed();
            }
        }
        private Nullable<global::System.Int32> _Int_1;
        partial void OnInt_1Changing(Nullable<global::System.Int32> value);
        partial void OnInt_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Decimal_1
        {
            get
            {
                return _Decimal_1;
            }
            set
            {
                OnDecimal_1Changing(value);
                ReportPropertyChanging("Decimal_1");
                _Decimal_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Decimal_1");
                OnDecimal_1Changed();
            }
        }
        private Nullable<global::System.Decimal> _Decimal_1;
        partial void OnDecimal_1Changing(Nullable<global::System.Decimal> value);
        partial void OnDecimal_1Changed();

        #endregion
    
    }

    #endregion
    
}
