//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("XERP", "FK_Company_CompanyCode", "CompanyCode", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(XERP.Server.DAL.CompanyDAL.CompanyCode), "Company", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.CompanyDAL.Company), true)]
[assembly: EdmRelationshipAttribute("XERP", "FK_Company_CompanyType", "CompanyType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(XERP.Server.DAL.CompanyDAL.CompanyType), "Company", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.CompanyDAL.Company), true)]
[assembly: EdmRelationshipAttribute("XERP", "FK_UdList_Company", "Company", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XERP.Server.DAL.CompanyDAL.Company), "UdList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.CompanyDAL.UdList), true)]
[assembly: EdmRelationshipAttribute("XERP", "FK_UdListItem_Company", "Company", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XERP.Server.DAL.CompanyDAL.Company), "UdListItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.CompanyDAL.UdListItem), true)]
[assembly: EdmRelationshipAttribute("XERP", "FK_UdListItem_UdList", "UdList", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XERP.Server.DAL.CompanyDAL.UdList), "UdListItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XERP.Server.DAL.CompanyDAL.UdListItem), true)]

#endregion

namespace XERP.Server.DAL.CompanyDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CompanyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CompanyEntities object using the connection string found in the 'CompanyEntities' section of the application configuration file.
        /// </summary>
        public CompanyEntities() : base("name=CompanyEntities", "CompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CompanyEntities object.
        /// </summary>
        public CompanyEntities(string connectionString) : base(connectionString, "CompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CompanyEntities object.
        /// </summary>
        public CompanyEntities(EntityConnection connection) : base(connection, "CompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Temp> Temps
        {
            get
            {
                if ((_Temps == null))
                {
                    _Temps = base.CreateObjectSet<Temp>("Temps");
                }
                return _Temps;
            }
        }
        private ObjectSet<Temp> _Temps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company> Companies
        {
            get
            {
                if ((_Companies == null))
                {
                    _Companies = base.CreateObjectSet<Company>("Companies");
                }
                return _Companies;
            }
        }
        private ObjectSet<Company> _Companies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CompanyCode> CompanyCodes
        {
            get
            {
                if ((_CompanyCodes == null))
                {
                    _CompanyCodes = base.CreateObjectSet<CompanyCode>("CompanyCodes");
                }
                return _CompanyCodes;
            }
        }
        private ObjectSet<CompanyCode> _CompanyCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CompanyType> CompanyTypes
        {
            get
            {
                if ((_CompanyTypes == null))
                {
                    _CompanyTypes = base.CreateObjectSet<CompanyType>("CompanyTypes");
                }
                return _CompanyTypes;
            }
        }
        private ObjectSet<CompanyType> _CompanyTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UdListItem> UdListItems
        {
            get
            {
                if ((_UdListItems == null))
                {
                    _UdListItems = base.CreateObjectSet<UdListItem>("UdListItems");
                }
                return _UdListItems;
            }
        }
        private ObjectSet<UdListItem> _UdListItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UdList> UdLists
        {
            get
            {
                if ((_UdLists == null))
                {
                    _UdLists = base.CreateObjectSet<UdList>("UdLists");
                }
                return _UdLists;
            }
        }
        private ObjectSet<UdList> _UdLists;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Temps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemps(Temp temp)
        {
            base.AddObject("Temps", temp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Companies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompanyCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanyCodes(CompanyCode companyCode)
        {
            base.AddObject("CompanyCodes", companyCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompanyTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanyTypes(CompanyType companyType)
        {
            base.AddObject("CompanyTypes", companyType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UdListItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUdListItems(UdListItem udListItem)
        {
            base.AddObject("UdListItems", udListItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UdLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUdLists(UdList udList)
        {
            base.AddObject("UdLists", udList);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP", Name="Company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static Company CreateCompany(global::System.String companyID, global::System.Int64 autoID)
        {
            Company company = new Company();
            company.CompanyID = companyID;
            company.AutoID = autoID;
            return company;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                if (_CompanyID != value)
                {
                    OnCompanyIDChanging(value);
                    ReportPropertyChanging("CompanyID");
                    _CompanyID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyID");
                    OnCompanyIDChanged();
                }
            }
        }
        private global::System.String _CompanyID;
        partial void OnCompanyIDChanging(global::System.String value);
        partial void OnCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyTypeID
        {
            get
            {
                return _CompanyTypeID;
            }
            set
            {
                OnCompanyTypeIDChanging(value);
                ReportPropertyChanging("CompanyTypeID");
                _CompanyTypeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyTypeID");
                OnCompanyTypeIDChanged();
            }
        }
        private global::System.String _CompanyTypeID;
        partial void OnCompanyTypeIDChanging(global::System.String value);
        partial void OnCompanyTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyCodeID
        {
            get
            {
                return _CompanyCodeID;
            }
            set
            {
                OnCompanyCodeIDChanging(value);
                ReportPropertyChanging("CompanyCodeID");
                _CompanyCodeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyCodeID");
                OnCompanyCodeIDChanged();
            }
        }
        private global::System.String _CompanyCodeID;
        partial void OnCompanyCodeIDChanging(global::System.String value);
        partial void OnCompanyCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateTaxCode
        {
            get
            {
                return _StateTaxCode;
            }
            set
            {
                OnStateTaxCodeChanging(value);
                ReportPropertyChanging("StateTaxCode");
                _StateTaxCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateTaxCode");
                OnStateTaxCodeChanged();
            }
        }
        private global::System.String _StateTaxCode;
        partial void OnStateTaxCodeChanging(global::System.String value);
        partial void OnStateTaxCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaxRegionCode
        {
            get
            {
                return _TaxRegionCode;
            }
            set
            {
                OnTaxRegionCodeChanging(value);
                ReportPropertyChanging("TaxRegionCode");
                _TaxRegionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaxRegionCode");
                OnTaxRegionCodeChanged();
            }
        }
        private global::System.String _TaxRegionCode;
        partial void OnTaxRegionCodeChanging(global::System.String value);
        partial void OnTaxRegionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CurrentFiscalYear
        {
            get
            {
                return _CurrentFiscalYear;
            }
            set
            {
                OnCurrentFiscalYearChanging(value);
                ReportPropertyChanging("CurrentFiscalYear");
                _CurrentFiscalYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentFiscalYear");
                OnCurrentFiscalYearChanged();
            }
        }
        private Nullable<global::System.Int32> _CurrentFiscalYear;
        partial void OnCurrentFiscalYearChanging(Nullable<global::System.Int32> value);
        partial void OnCurrentFiscalYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultExecutablePath
        {
            get
            {
                return _DefaultExecutablePath;
            }
            set
            {
                OnDefaultExecutablePathChanging(value);
                ReportPropertyChanging("DefaultExecutablePath");
                _DefaultExecutablePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultExecutablePath");
                OnDefaultExecutablePathChanged();
            }
        }
        private global::System.String _DefaultExecutablePath;
        partial void OnDefaultExecutablePathChanging(global::System.String value);
        partial void OnDefaultExecutablePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address3
        {
            get
            {
                return _Address3;
            }
            set
            {
                OnAddress3Changing(value);
                ReportPropertyChanging("Address3");
                _Address3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address3");
                OnAddress3Changed();
            }
        }
        private global::System.String _Address3;
        partial void OnAddress3Changing(global::System.String value);
        partial void OnAddress3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNum
        {
            get
            {
                return _PhoneNum;
            }
            set
            {
                OnPhoneNumChanging(value);
                ReportPropertyChanging("PhoneNum");
                _PhoneNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNum");
                OnPhoneNumChanged();
            }
        }
        private global::System.String _PhoneNum;
        partial void OnPhoneNumChanging(global::System.String value);
        partial void OnPhoneNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNum2
        {
            get
            {
                return _PhoneNum2;
            }
            set
            {
                OnPhoneNum2Changing(value);
                ReportPropertyChanging("PhoneNum2");
                _PhoneNum2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNum2");
                OnPhoneNum2Changed();
            }
        }
        private global::System.String _PhoneNum2;
        partial void OnPhoneNum2Changing(global::System.String value);
        partial void OnPhoneNum2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FaxNum
        {
            get
            {
                return _FaxNum;
            }
            set
            {
                OnFaxNumChanging(value);
                ReportPropertyChanging("FaxNum");
                _FaxNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FaxNum");
                OnFaxNumChanged();
            }
        }
        private global::System.String _FaxNum;
        partial void OnFaxNumChanging(global::System.String value);
        partial void OnFaxNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email2
        {
            get
            {
                return _Email2;
            }
            set
            {
                OnEmail2Changing(value);
                ReportPropertyChanging("Email2");
                _Email2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email2");
                OnEmail2Changed();
            }
        }
        private global::System.String _Email2;
        partial void OnEmail2Changing(global::System.String value);
        partial void OnEmail2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsExpanded
        {
            get
            {
                return _IsExpanded;
            }
            set
            {
                OnIsExpandedChanging(value);
                ReportPropertyChanging("IsExpanded");
                _IsExpanded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExpanded");
                OnIsExpandedChanged();
            }
        }
        private Nullable<global::System.Byte> _IsExpanded;
        partial void OnIsExpandedChanging(Nullable<global::System.Byte> value);
        partial void OnIsExpandedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private Nullable<global::System.Byte> _IsValid;
        partial void OnIsValidChanging(Nullable<global::System.Byte> value);
        partial void OnIsValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NotValidMessage
        {
            get
            {
                return _NotValidMessage;
            }
            set
            {
                OnNotValidMessageChanging(value);
                ReportPropertyChanging("NotValidMessage");
                _NotValidMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NotValidMessage");
                OnNotValidMessageChanged();
            }
        }
        private global::System.String _NotValidMessage;
        partial void OnNotValidMessageChanging(global::System.String value);
        partial void OnNotValidMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedByDate
        {
            get
            {
                return _LastModifiedByDate;
            }
            set
            {
                OnLastModifiedByDateChanging(value);
                ReportPropertyChanging("LastModifiedByDate");
                _LastModifiedByDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedByDate");
                OnLastModifiedByDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedByDate;
        partial void OnLastModifiedByDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedByDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSelected
        {
            get
            {
                return _IsSelected;
            }
            set
            {
                OnIsSelectedChanging(value);
                ReportPropertyChanging("IsSelected");
                _IsSelected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSelected");
                OnIsSelectedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSelected;
        partial void OnIsSelectedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSelectedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_Company_CompanyCode", "CompanyCode")]
        public CompanyCode CompanyCode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CompanyCode>("XERP.FK_Company_CompanyCode", "CompanyCode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CompanyCode>("XERP.FK_Company_CompanyCode", "CompanyCode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CompanyCode> CompanyCodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CompanyCode>("XERP.FK_Company_CompanyCode", "CompanyCode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CompanyCode>("XERP.FK_Company_CompanyCode", "CompanyCode", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_Company_CompanyType", "CompanyType")]
        public CompanyType CompanyType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CompanyType>("XERP.FK_Company_CompanyType", "CompanyType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CompanyType>("XERP.FK_Company_CompanyType", "CompanyType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CompanyType> CompanyTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CompanyType>("XERP.FK_Company_CompanyType", "CompanyType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CompanyType>("XERP.FK_Company_CompanyType", "CompanyType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_UdList_Company", "UdList")]
        public EntityCollection<UdList> UdLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UdList>("XERP.FK_UdList_Company", "UdList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UdList>("XERP.FK_UdList_Company", "UdList", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_UdListItem_Company", "UdListItem")]
        public EntityCollection<UdListItem> UdListItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UdListItem>("XERP.FK_UdListItem_Company", "UdListItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UdListItem>("XERP.FK_UdListItem_Company", "UdListItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP", Name="CompanyCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CompanyCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CompanyCode object.
        /// </summary>
        /// <param name="companyCodeID">Initial value of the CompanyCodeID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static CompanyCode CreateCompanyCode(global::System.String companyCodeID, global::System.Int64 autoID)
        {
            CompanyCode companyCode = new CompanyCode();
            companyCode.CompanyCodeID = companyCodeID;
            companyCode.AutoID = autoID;
            return companyCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyCodeID
        {
            get
            {
                return _CompanyCodeID;
            }
            set
            {
                if (_CompanyCodeID != value)
                {
                    OnCompanyCodeIDChanging(value);
                    ReportPropertyChanging("CompanyCodeID");
                    _CompanyCodeID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyCodeID");
                    OnCompanyCodeIDChanged();
                }
            }
        }
        private global::System.String _CompanyCodeID;
        partial void OnCompanyCodeIDChanging(global::System.String value);
        partial void OnCompanyCodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsExpanded
        {
            get
            {
                return _IsExpanded;
            }
            set
            {
                OnIsExpandedChanging(value);
                ReportPropertyChanging("IsExpanded");
                _IsExpanded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExpanded");
                OnIsExpandedChanged();
            }
        }
        private Nullable<global::System.Byte> _IsExpanded;
        partial void OnIsExpandedChanging(Nullable<global::System.Byte> value);
        partial void OnIsExpandedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private Nullable<global::System.Byte> _IsValid;
        partial void OnIsValidChanging(Nullable<global::System.Byte> value);
        partial void OnIsValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NotValidMessage
        {
            get
            {
                return _NotValidMessage;
            }
            set
            {
                OnNotValidMessageChanging(value);
                ReportPropertyChanging("NotValidMessage");
                _NotValidMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NotValidMessage");
                OnNotValidMessageChanged();
            }
        }
        private global::System.String _NotValidMessage;
        partial void OnNotValidMessageChanging(global::System.String value);
        partial void OnNotValidMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedByDate
        {
            get
            {
                return _LastModifiedByDate;
            }
            set
            {
                OnLastModifiedByDateChanging(value);
                ReportPropertyChanging("LastModifiedByDate");
                _LastModifiedByDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedByDate");
                OnLastModifiedByDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedByDate;
        partial void OnLastModifiedByDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedByDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSelected
        {
            get
            {
                return _IsSelected;
            }
            set
            {
                OnIsSelectedChanging(value);
                ReportPropertyChanging("IsSelected");
                _IsSelected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSelected");
                OnIsSelectedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSelected;
        partial void OnIsSelectedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSelectedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_Company_CompanyCode", "Company")]
        public EntityCollection<Company> Companies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Company>("XERP.FK_Company_CompanyCode", "Company");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Company>("XERP.FK_Company_CompanyCode", "Company", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP", Name="CompanyType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CompanyType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CompanyType object.
        /// </summary>
        /// <param name="companyTypeID">Initial value of the CompanyTypeID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static CompanyType CreateCompanyType(global::System.String companyTypeID, global::System.Int64 autoID)
        {
            CompanyType companyType = new CompanyType();
            companyType.CompanyTypeID = companyTypeID;
            companyType.AutoID = autoID;
            return companyType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyTypeID
        {
            get
            {
                return _CompanyTypeID;
            }
            set
            {
                if (_CompanyTypeID != value)
                {
                    OnCompanyTypeIDChanging(value);
                    ReportPropertyChanging("CompanyTypeID");
                    _CompanyTypeID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyTypeID");
                    OnCompanyTypeIDChanged();
                }
            }
        }
        private global::System.String _CompanyTypeID;
        partial void OnCompanyTypeIDChanging(global::System.String value);
        partial void OnCompanyTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsExpanded
        {
            get
            {
                return _IsExpanded;
            }
            set
            {
                OnIsExpandedChanging(value);
                ReportPropertyChanging("IsExpanded");
                _IsExpanded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExpanded");
                OnIsExpandedChanged();
            }
        }
        private Nullable<global::System.Byte> _IsExpanded;
        partial void OnIsExpandedChanging(Nullable<global::System.Byte> value);
        partial void OnIsExpandedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private Nullable<global::System.Byte> _IsValid;
        partial void OnIsValidChanging(Nullable<global::System.Byte> value);
        partial void OnIsValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NotValidMessage
        {
            get
            {
                return _NotValidMessage;
            }
            set
            {
                OnNotValidMessageChanging(value);
                ReportPropertyChanging("NotValidMessage");
                _NotValidMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NotValidMessage");
                OnNotValidMessageChanged();
            }
        }
        private global::System.String _NotValidMessage;
        partial void OnNotValidMessageChanging(global::System.String value);
        partial void OnNotValidMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedByDate
        {
            get
            {
                return _LastModifiedByDate;
            }
            set
            {
                OnLastModifiedByDateChanging(value);
                ReportPropertyChanging("LastModifiedByDate");
                _LastModifiedByDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedByDate");
                OnLastModifiedByDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedByDate;
        partial void OnLastModifiedByDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedByDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSelected
        {
            get
            {
                return _IsSelected;
            }
            set
            {
                OnIsSelectedChanging(value);
                ReportPropertyChanging("IsSelected");
                _IsSelected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSelected");
                OnIsSelectedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSelected;
        partial void OnIsSelectedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSelectedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_Company_CompanyType", "Company")]
        public EntityCollection<Company> Companies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Company>("XERP.FK_Company_CompanyType", "Company");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Company>("XERP.FK_Company_CompanyType", "Company", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP", Name="Temp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Temp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Temp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Temp CreateTemp(global::System.Int64 id)
        {
            Temp temp = new Temp();
            temp.ID = id;
            return temp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Bool_1
        {
            get
            {
                return _Bool_1;
            }
            set
            {
                OnBool_1Changing(value);
                ReportPropertyChanging("Bool_1");
                _Bool_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bool_1");
                OnBool_1Changed();
            }
        }
        private Nullable<global::System.Boolean> _Bool_1;
        partial void OnBool_1Changing(Nullable<global::System.Boolean> value);
        partial void OnBool_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortChar_1
        {
            get
            {
                return _ShortChar_1;
            }
            set
            {
                OnShortChar_1Changing(value);
                ReportPropertyChanging("ShortChar_1");
                _ShortChar_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortChar_1");
                OnShortChar_1Changed();
            }
        }
        private global::System.String _ShortChar_1;
        partial void OnShortChar_1Changing(global::System.String value);
        partial void OnShortChar_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Int_1
        {
            get
            {
                return _Int_1;
            }
            set
            {
                OnInt_1Changing(value);
                ReportPropertyChanging("Int_1");
                _Int_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Int_1");
                OnInt_1Changed();
            }
        }
        private Nullable<global::System.Int32> _Int_1;
        partial void OnInt_1Changing(Nullable<global::System.Int32> value);
        partial void OnInt_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Decimal_1
        {
            get
            {
                return _Decimal_1;
            }
            set
            {
                OnDecimal_1Changing(value);
                ReportPropertyChanging("Decimal_1");
                _Decimal_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Decimal_1");
                OnDecimal_1Changed();
            }
        }
        private Nullable<global::System.Decimal> _Decimal_1;
        partial void OnDecimal_1Changing(Nullable<global::System.Decimal> value);
        partial void OnDecimal_1Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP", Name="UdList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UdList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UdList object.
        /// </summary>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        /// <param name="udListID">Initial value of the UdListID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static UdList CreateUdList(global::System.String companyID, global::System.String udListID, global::System.Int64 autoID)
        {
            UdList udList = new UdList();
            udList.CompanyID = companyID;
            udList.UdListID = udListID;
            udList.AutoID = autoID;
            return udList;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                if (_CompanyID != value)
                {
                    OnCompanyIDChanging(value);
                    ReportPropertyChanging("CompanyID");
                    _CompanyID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyID");
                    OnCompanyIDChanged();
                }
            }
        }
        private global::System.String _CompanyID;
        partial void OnCompanyIDChanging(global::System.String value);
        partial void OnCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UdListID
        {
            get
            {
                return _UdListID;
            }
            set
            {
                if (_UdListID != value)
                {
                    OnUdListIDChanging(value);
                    ReportPropertyChanging("UdListID");
                    _UdListID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UdListID");
                    OnUdListIDChanged();
                }
            }
        }
        private global::System.String _UdListID;
        partial void OnUdListIDChanging(global::System.String value);
        partial void OnUdListIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSelected
        {
            get
            {
                return _IsSelected;
            }
            set
            {
                OnIsSelectedChanging(value);
                ReportPropertyChanging("IsSelected");
                _IsSelected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSelected");
                OnIsSelectedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSelected;
        partial void OnIsSelectedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSelectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsExpanded
        {
            get
            {
                return _IsExpanded;
            }
            set
            {
                OnIsExpandedChanging(value);
                ReportPropertyChanging("IsExpanded");
                _IsExpanded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExpanded");
                OnIsExpandedChanged();
            }
        }
        private Nullable<global::System.Byte> _IsExpanded;
        partial void OnIsExpandedChanging(Nullable<global::System.Byte> value);
        partial void OnIsExpandedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private Nullable<global::System.Byte> _IsValid;
        partial void OnIsValidChanging(Nullable<global::System.Byte> value);
        partial void OnIsValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NotValidMessage
        {
            get
            {
                return _NotValidMessage;
            }
            set
            {
                OnNotValidMessageChanging(value);
                ReportPropertyChanging("NotValidMessage");
                _NotValidMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NotValidMessage");
                OnNotValidMessageChanged();
            }
        }
        private global::System.String _NotValidMessage;
        partial void OnNotValidMessageChanging(global::System.String value);
        partial void OnNotValidMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedByDate
        {
            get
            {
                return _LastModifiedByDate;
            }
            set
            {
                OnLastModifiedByDateChanging(value);
                ReportPropertyChanging("LastModifiedByDate");
                _LastModifiedByDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedByDate");
                OnLastModifiedByDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedByDate;
        partial void OnLastModifiedByDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedByDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_UdList_Company", "Company")]
        public Company Company
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.FK_UdList_Company", "Company").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.FK_UdList_Company", "Company").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Company> CompanyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.FK_UdList_Company", "Company");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Company>("XERP.FK_UdList_Company", "Company", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_UdListItem_UdList", "UdListItem")]
        public EntityCollection<UdListItem> UdListItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UdListItem>("XERP.FK_UdListItem_UdList", "UdListItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UdListItem>("XERP.FK_UdListItem_UdList", "UdListItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XERP", Name="UdListItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UdListItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UdListItem object.
        /// </summary>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        /// <param name="udListID">Initial value of the UdListID property.</param>
        /// <param name="udListItemID">Initial value of the UdListItemID property.</param>
        /// <param name="autoID">Initial value of the AutoID property.</param>
        public static UdListItem CreateUdListItem(global::System.String companyID, global::System.String udListID, global::System.String udListItemID, global::System.Int64 autoID)
        {
            UdListItem udListItem = new UdListItem();
            udListItem.CompanyID = companyID;
            udListItem.UdListID = udListID;
            udListItem.UdListItemID = udListItemID;
            udListItem.AutoID = autoID;
            return udListItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                if (_CompanyID != value)
                {
                    OnCompanyIDChanging(value);
                    ReportPropertyChanging("CompanyID");
                    _CompanyID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanyID");
                    OnCompanyIDChanged();
                }
            }
        }
        private global::System.String _CompanyID;
        partial void OnCompanyIDChanging(global::System.String value);
        partial void OnCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UdListID
        {
            get
            {
                return _UdListID;
            }
            set
            {
                if (_UdListID != value)
                {
                    OnUdListIDChanging(value);
                    ReportPropertyChanging("UdListID");
                    _UdListID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UdListID");
                    OnUdListIDChanged();
                }
            }
        }
        private global::System.String _UdListID;
        partial void OnUdListIDChanging(global::System.String value);
        partial void OnUdListIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UdListItemID
        {
            get
            {
                return _UdListItemID;
            }
            set
            {
                if (_UdListItemID != value)
                {
                    OnUdListItemIDChanging(value);
                    ReportPropertyChanging("UdListItemID");
                    _UdListItemID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UdListItemID");
                    OnUdListItemIDChanged();
                }
            }
        }
        private global::System.String _UdListItemID;
        partial void OnUdListItemIDChanging(global::System.String value);
        partial void OnUdListItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoID
        {
            get
            {
                return _AutoID;
            }
            set
            {
                OnAutoIDChanging(value);
                ReportPropertyChanging("AutoID");
                _AutoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AutoID");
                OnAutoIDChanged();
            }
        }
        private global::System.Int64 _AutoID;
        partial void OnAutoIDChanging(global::System.Int64 value);
        partial void OnAutoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSelected
        {
            get
            {
                return _IsSelected;
            }
            set
            {
                OnIsSelectedChanging(value);
                ReportPropertyChanging("IsSelected");
                _IsSelected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSelected");
                OnIsSelectedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSelected;
        partial void OnIsSelectedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSelectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsExpanded
        {
            get
            {
                return _IsExpanded;
            }
            set
            {
                OnIsExpandedChanging(value);
                ReportPropertyChanging("IsExpanded");
                _IsExpanded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsExpanded");
                OnIsExpandedChanged();
            }
        }
        private Nullable<global::System.Byte> _IsExpanded;
        partial void OnIsExpandedChanging(Nullable<global::System.Byte> value);
        partial void OnIsExpandedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private Nullable<global::System.Byte> _IsValid;
        partial void OnIsValidChanging(Nullable<global::System.Byte> value);
        partial void OnIsValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NotValidMessage
        {
            get
            {
                return _NotValidMessage;
            }
            set
            {
                OnNotValidMessageChanging(value);
                ReportPropertyChanging("NotValidMessage");
                _NotValidMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NotValidMessage");
                OnNotValidMessageChanged();
            }
        }
        private global::System.String _NotValidMessage;
        partial void OnNotValidMessageChanging(global::System.String value);
        partial void OnNotValidMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedByDate
        {
            get
            {
                return _LastModifiedByDate;
            }
            set
            {
                OnLastModifiedByDateChanging(value);
                ReportPropertyChanging("LastModifiedByDate");
                _LastModifiedByDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedByDate");
                OnLastModifiedByDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedByDate;
        partial void OnLastModifiedByDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedByDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_UdListItem_Company", "Company")]
        public Company Company
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.FK_UdListItem_Company", "Company").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.FK_UdListItem_Company", "Company").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Company> CompanyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Company>("XERP.FK_UdListItem_Company", "Company");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Company>("XERP.FK_UdListItem_Company", "Company", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XERP", "FK_UdListItem_UdList", "UdList")]
        public UdList UdList
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UdList>("XERP.FK_UdListItem_UdList", "UdList").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UdList>("XERP.FK_UdListItem_UdList", "UdList").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UdList> UdListReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UdList>("XERP.FK_UdListItem_UdList", "UdList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UdList>("XERP.FK_UdListItem_UdList", "UdList", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
