
namespace XERP.Client.WPF.MenuItemMaintenance
{//use this class to share properties amonst views, viewmodels etc...
    public class GlobalProperties
    {//MenuItemMaintenace is the exutable program that this Maintenance UI is tied to...
        //All UI's used within this project will inherit this executableprogram's security privelages...
        //this program name coencides with db table ExecutablPrograms...
        //MenuItems are then applied to the ExecutablePrograms allotting for custom form athentication...
        private const string _executableProgramName = "MenuItemMaintenance";
        public string ExecutableProgramName
        {
            get { return _executableProgramName; }
        } 

    }
}
