//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 3/16/2012 12:17:52 PM
namespace XERP.LogInDomain.LogInDataService
{
    
    /// <summary>
    /// There are no comments for LogInEntities in the schema.
    /// </summary>
    public partial class LogInEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new LogInEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LogInEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("XERP.LogIn.DAL.LogInDAL", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("XERP.LogInDomain.LogInDataService", typeName.Substring(23)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("XERP.LogInDomain.LogInDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("XERP.LogIn.DAL.LogInDAL.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Company> Companies
        {
            get
            {
                if ((this._Companies == null))
                {
                    this._Companies = base.CreateQuery<Company>("Companies");
                }
                return this._Companies;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Company> _Companies;
        /// <summary>
        /// There are no comments for SecurityGroups in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SecurityGroup> SecurityGroups
        {
            get
            {
                if ((this._SecurityGroups == null))
                {
                    this._SecurityGroups = base.CreateQuery<SecurityGroup>("SecurityGroups");
                }
                return this._SecurityGroups;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SecurityGroup> _SecurityGroups;
        /// <summary>
        /// There are no comments for SystemUserCodes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SystemUserCode> SystemUserCodes
        {
            get
            {
                if ((this._SystemUserCodes == null))
                {
                    this._SystemUserCodes = base.CreateQuery<SystemUserCode>("SystemUserCodes");
                }
                return this._SystemUserCodes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SystemUserCode> _SystemUserCodes;
        /// <summary>
        /// There are no comments for SystemUserSecurities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SystemUserSecurity> SystemUserSecurities
        {
            get
            {
                if ((this._SystemUserSecurities == null))
                {
                    this._SystemUserSecurities = base.CreateQuery<SystemUserSecurity>("SystemUserSecurities");
                }
                return this._SystemUserSecurities;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SystemUserSecurity> _SystemUserSecurities;
        /// <summary>
        /// There are no comments for SystemUserTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SystemUserType> SystemUserTypes
        {
            get
            {
                if ((this._SystemUserTypes == null))
                {
                    this._SystemUserTypes = base.CreateQuery<SystemUserType>("SystemUserTypes");
                }
                return this._SystemUserTypes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SystemUserType> _SystemUserTypes;
        /// <summary>
        /// There are no comments for Temps in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Temp> Temps
        {
            get
            {
                if ((this._Temps == null))
                {
                    this._Temps = base.CreateQuery<Temp>("Temps");
                }
                return this._Temps;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Temp> _Temps;
        /// <summary>
        /// There are no comments for SystemUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SystemUser> SystemUsers
        {
            get
            {
                if ((this._SystemUsers == null))
                {
                    this._SystemUsers = base.CreateQuery<SystemUser>("SystemUsers");
                }
                return this._SystemUsers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SystemUser> _SystemUsers;
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
        /// <summary>
        /// There are no comments for SecurityGroups in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSecurityGroups(SecurityGroup securityGroup)
        {
            base.AddObject("SecurityGroups", securityGroup);
        }
        /// <summary>
        /// There are no comments for SystemUserCodes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSystemUserCodes(SystemUserCode systemUserCode)
        {
            base.AddObject("SystemUserCodes", systemUserCode);
        }
        /// <summary>
        /// There are no comments for SystemUserSecurities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSystemUserSecurities(SystemUserSecurity systemUserSecurity)
        {
            base.AddObject("SystemUserSecurities", systemUserSecurity);
        }
        /// <summary>
        /// There are no comments for SystemUserTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSystemUserTypes(SystemUserType systemUserType)
        {
            base.AddObject("SystemUserTypes", systemUserType);
        }
        /// <summary>
        /// There are no comments for Temps in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTemps(Temp temp)
        {
            base.AddObject("Temps", temp);
        }
        /// <summary>
        /// There are no comments for SystemUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSystemUsers(SystemUser systemUser)
        {
            base.AddObject("SystemUsers", systemUser);
        }
    }
    /// <summary>
    /// There are no comments for XERP.LogIn.DAL.LogInDAL.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CompanyID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Companies")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CompanyID")]
    public partial class Company : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="companyID">Initial value of CompanyID.</param>
        /// <param name="autoID">Initial value of AutoID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Company CreateCompany(string companyID, long autoID)
        {
            Company company = new Company();
            company.CompanyID = companyID;
            company.AutoID = autoID;
            return company;
        }
        /// <summary>
        /// There are no comments for Property CompanyID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this.OnCompanyIDChanging(value);
                this._CompanyID = value;
                this.OnCompanyIDChanged();
                this.OnPropertyChanged("CompanyID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CompanyID;
        partial void OnCompanyIDChanging(string value);
        partial void OnCompanyIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Active;
        partial void OnActiveChanging(global::System.Nullable<bool> value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property CompanyTypeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CompanyTypeID
        {
            get
            {
                return this._CompanyTypeID;
            }
            set
            {
                this.OnCompanyTypeIDChanging(value);
                this._CompanyTypeID = value;
                this.OnCompanyTypeIDChanged();
                this.OnPropertyChanged("CompanyTypeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CompanyTypeID;
        partial void OnCompanyTypeIDChanging(string value);
        partial void OnCompanyTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CompanyCodeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CompanyCodeID
        {
            get
            {
                return this._CompanyCodeID;
            }
            set
            {
                this.OnCompanyCodeIDChanging(value);
                this._CompanyCodeID = value;
                this.OnCompanyCodeIDChanged();
                this.OnPropertyChanged("CompanyCodeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CompanyCodeID;
        partial void OnCompanyCodeIDChanging(string value);
        partial void OnCompanyCodeIDChanged();
        /// <summary>
        /// There are no comments for Property StateTaxCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StateTaxCode
        {
            get
            {
                return this._StateTaxCode;
            }
            set
            {
                this.OnStateTaxCodeChanging(value);
                this._StateTaxCode = value;
                this.OnStateTaxCodeChanged();
                this.OnPropertyChanged("StateTaxCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StateTaxCode;
        partial void OnStateTaxCodeChanging(string value);
        partial void OnStateTaxCodeChanged();
        /// <summary>
        /// There are no comments for Property TaxRegionCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TaxRegionCode
        {
            get
            {
                return this._TaxRegionCode;
            }
            set
            {
                this.OnTaxRegionCodeChanging(value);
                this._TaxRegionCode = value;
                this.OnTaxRegionCodeChanged();
                this.OnPropertyChanged("TaxRegionCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TaxRegionCode;
        partial void OnTaxRegionCodeChanging(string value);
        partial void OnTaxRegionCodeChanged();
        /// <summary>
        /// There are no comments for Property CurrentFiscalYear in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> CurrentFiscalYear
        {
            get
            {
                return this._CurrentFiscalYear;
            }
            set
            {
                this.OnCurrentFiscalYearChanging(value);
                this._CurrentFiscalYear = value;
                this.OnCurrentFiscalYearChanged();
                this.OnPropertyChanged("CurrentFiscalYear");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _CurrentFiscalYear;
        partial void OnCurrentFiscalYearChanging(global::System.Nullable<int> value);
        partial void OnCurrentFiscalYearChanged();
        /// <summary>
        /// There are no comments for Property DefaultExecutablePath in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DefaultExecutablePath
        {
            get
            {
                return this._DefaultExecutablePath;
            }
            set
            {
                this.OnDefaultExecutablePathChanging(value);
                this._DefaultExecutablePath = value;
                this.OnDefaultExecutablePathChanged();
                this.OnPropertyChanged("DefaultExecutablePath");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DefaultExecutablePath;
        partial void OnDefaultExecutablePathChanging(string value);
        partial void OnDefaultExecutablePathChanged();
        /// <summary>
        /// There are no comments for Property Address1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address1
        {
            get
            {
                return this._Address1;
            }
            set
            {
                this.OnAddress1Changing(value);
                this._Address1 = value;
                this.OnAddress1Changed();
                this.OnPropertyChanged("Address1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address1;
        partial void OnAddress1Changing(string value);
        partial void OnAddress1Changed();
        /// <summary>
        /// There are no comments for Property Address2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address2
        {
            get
            {
                return this._Address2;
            }
            set
            {
                this.OnAddress2Changing(value);
                this._Address2 = value;
                this.OnAddress2Changed();
                this.OnPropertyChanged("Address2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address2;
        partial void OnAddress2Changing(string value);
        partial void OnAddress2Changed();
        /// <summary>
        /// There are no comments for Property Address3 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address3
        {
            get
            {
                return this._Address3;
            }
            set
            {
                this.OnAddress3Changing(value);
                this._Address3 = value;
                this.OnAddress3Changed();
                this.OnPropertyChanged("Address3");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address3;
        partial void OnAddress3Changing(string value);
        partial void OnAddress3Changed();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property Zip in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this.OnZipChanging(value);
                this._Zip = value;
                this.OnZipChanged();
                this.OnPropertyChanged("Zip");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Zip;
        partial void OnZipChanging(string value);
        partial void OnZipChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property PhoneNum in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneNum
        {
            get
            {
                return this._PhoneNum;
            }
            set
            {
                this.OnPhoneNumChanging(value);
                this._PhoneNum = value;
                this.OnPhoneNumChanged();
                this.OnPropertyChanged("PhoneNum");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneNum;
        partial void OnPhoneNumChanging(string value);
        partial void OnPhoneNumChanged();
        /// <summary>
        /// There are no comments for Property PhoneNum2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneNum2
        {
            get
            {
                return this._PhoneNum2;
            }
            set
            {
                this.OnPhoneNum2Changing(value);
                this._PhoneNum2 = value;
                this.OnPhoneNum2Changed();
                this.OnPropertyChanged("PhoneNum2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneNum2;
        partial void OnPhoneNum2Changing(string value);
        partial void OnPhoneNum2Changed();
        /// <summary>
        /// There are no comments for Property FaxNum in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FaxNum
        {
            get
            {
                return this._FaxNum;
            }
            set
            {
                this.OnFaxNumChanging(value);
                this._FaxNum = value;
                this.OnFaxNumChanged();
                this.OnPropertyChanged("FaxNum");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FaxNum;
        partial void OnFaxNumChanging(string value);
        partial void OnFaxNumChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Email2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email2
        {
            get
            {
                return this._Email2;
            }
            set
            {
                this.OnEmail2Changing(value);
                this._Email2 = value;
                this.OnEmail2Changed();
                this.OnPropertyChanged("Email2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email2;
        partial void OnEmail2Changing(string value);
        partial void OnEmail2Changed();
        /// <summary>
        /// There are no comments for Property AutoID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long AutoID
        {
            get
            {
                return this._AutoID;
            }
            set
            {
                this.OnAutoIDChanging(value);
                this._AutoID = value;
                this.OnAutoIDChanged();
                this.OnPropertyChanged("AutoID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _AutoID;
        partial void OnAutoIDChanging(long value);
        partial void OnAutoIDChanged();
        /// <summary>
        /// There are no comments for SecurityGroups in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SecurityGroup> SecurityGroups
        {
            get
            {
                return this._SecurityGroups;
            }
            set
            {
                this._SecurityGroups = value;
                this.OnPropertyChanged("SecurityGroups");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SecurityGroup> _SecurityGroups = new global::System.Data.Services.Client.DataServiceCollection<SecurityGroup>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for SystemUserSecurities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity> SystemUserSecurities
        {
            get
            {
                return this._SystemUserSecurities;
            }
            set
            {
                this._SystemUserSecurities = value;
                this.OnPropertyChanged("SystemUserSecurities");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity> _SystemUserSecurities = new global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for XERP.LogIn.DAL.LogInDAL.SecurityGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CompanyID
    /// SecurityGroupID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SecurityGroups")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CompanyID", "SecurityGroupID")]
    public partial class SecurityGroup : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SecurityGroup object.
        /// </summary>
        /// <param name="companyID">Initial value of CompanyID.</param>
        /// <param name="securityGroupID">Initial value of SecurityGroupID.</param>
        /// <param name="autoID">Initial value of AutoID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SecurityGroup CreateSecurityGroup(string companyID, string securityGroupID, long autoID)
        {
            SecurityGroup securityGroup = new SecurityGroup();
            securityGroup.CompanyID = companyID;
            securityGroup.SecurityGroupID = securityGroupID;
            securityGroup.AutoID = autoID;
            return securityGroup;
        }
        /// <summary>
        /// There are no comments for Property CompanyID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this.OnCompanyIDChanging(value);
                this._CompanyID = value;
                this.OnCompanyIDChanged();
                this.OnPropertyChanged("CompanyID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CompanyID;
        partial void OnCompanyIDChanging(string value);
        partial void OnCompanyIDChanged();
        /// <summary>
        /// There are no comments for Property SecurityGroupID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecurityGroupID
        {
            get
            {
                return this._SecurityGroupID;
            }
            set
            {
                this.OnSecurityGroupIDChanging(value);
                this._SecurityGroupID = value;
                this.OnSecurityGroupIDChanged();
                this.OnPropertyChanged("SecurityGroupID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecurityGroupID;
        partial void OnSecurityGroupIDChanging(string value);
        partial void OnSecurityGroupIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Active;
        partial void OnActiveChanging(global::System.Nullable<bool> value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property SecurityGroupTypeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecurityGroupTypeID
        {
            get
            {
                return this._SecurityGroupTypeID;
            }
            set
            {
                this.OnSecurityGroupTypeIDChanging(value);
                this._SecurityGroupTypeID = value;
                this.OnSecurityGroupTypeIDChanged();
                this.OnPropertyChanged("SecurityGroupTypeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecurityGroupTypeID;
        partial void OnSecurityGroupTypeIDChanging(string value);
        partial void OnSecurityGroupTypeIDChanged();
        /// <summary>
        /// There are no comments for Property SecurityGroupCodeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecurityGroupCodeID
        {
            get
            {
                return this._SecurityGroupCodeID;
            }
            set
            {
                this.OnSecurityGroupCodeIDChanging(value);
                this._SecurityGroupCodeID = value;
                this.OnSecurityGroupCodeIDChanged();
                this.OnPropertyChanged("SecurityGroupCodeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecurityGroupCodeID;
        partial void OnSecurityGroupCodeIDChanging(string value);
        partial void OnSecurityGroupCodeIDChanged();
        /// <summary>
        /// There are no comments for Property AutoID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long AutoID
        {
            get
            {
                return this._AutoID;
            }
            set
            {
                this.OnAutoIDChanging(value);
                this._AutoID = value;
                this.OnAutoIDChanged();
                this.OnPropertyChanged("AutoID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _AutoID;
        partial void OnAutoIDChanging(long value);
        partial void OnAutoIDChanged();
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Company Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this._Company = value;
                this.OnPropertyChanged("Company");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Company _Company;
        /// <summary>
        /// There are no comments for SystemUserSecurities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity> SystemUserSecurities
        {
            get
            {
                return this._SystemUserSecurities;
            }
            set
            {
                this._SystemUserSecurities = value;
                this.OnPropertyChanged("SystemUserSecurities");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity> _SystemUserSecurities = new global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for XERP.LogIn.DAL.LogInDAL.SystemUserCode in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SystemUserCodeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SystemUserCodes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SystemUserCodeID")]
    public partial class SystemUserCode : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SystemUserCode object.
        /// </summary>
        /// <param name="systemUserCodeID">Initial value of SystemUserCodeID.</param>
        /// <param name="autoID">Initial value of AutoID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SystemUserCode CreateSystemUserCode(string systemUserCodeID, long autoID)
        {
            SystemUserCode systemUserCode = new SystemUserCode();
            systemUserCode.SystemUserCodeID = systemUserCodeID;
            systemUserCode.AutoID = autoID;
            return systemUserCode;
        }
        /// <summary>
        /// There are no comments for Property SystemUserCodeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SystemUserCodeID
        {
            get
            {
                return this._SystemUserCodeID;
            }
            set
            {
                this.OnSystemUserCodeIDChanging(value);
                this._SystemUserCodeID = value;
                this.OnSystemUserCodeIDChanged();
                this.OnPropertyChanged("SystemUserCodeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SystemUserCodeID;
        partial void OnSystemUserCodeIDChanging(string value);
        partial void OnSystemUserCodeIDChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property AutoID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long AutoID
        {
            get
            {
                return this._AutoID;
            }
            set
            {
                this.OnAutoIDChanging(value);
                this._AutoID = value;
                this.OnAutoIDChanged();
                this.OnPropertyChanged("AutoID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _AutoID;
        partial void OnAutoIDChanging(long value);
        partial void OnAutoIDChanged();
        /// <summary>
        /// There are no comments for SystemUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SystemUser> SystemUsers
        {
            get
            {
                return this._SystemUsers;
            }
            set
            {
                this._SystemUsers = value;
                this.OnPropertyChanged("SystemUsers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SystemUser> _SystemUsers = new global::System.Data.Services.Client.DataServiceCollection<SystemUser>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for XERP.LogIn.DAL.LogInDAL.SystemUserSecurity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CompanyID
    /// SystemUserID
    /// SecurityGroupID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SystemUserSecurities")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CompanyID", "SystemUserID", "SecurityGroupID")]
    public partial class SystemUserSecurity : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SystemUserSecurity object.
        /// </summary>
        /// <param name="companyID">Initial value of CompanyID.</param>
        /// <param name="systemUserID">Initial value of SystemUserID.</param>
        /// <param name="securityGroupID">Initial value of SecurityGroupID.</param>
        /// <param name="autoID">Initial value of AutoID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SystemUserSecurity CreateSystemUserSecurity(string companyID, string systemUserID, string securityGroupID, long autoID)
        {
            SystemUserSecurity systemUserSecurity = new SystemUserSecurity();
            systemUserSecurity.CompanyID = companyID;
            systemUserSecurity.SystemUserID = systemUserID;
            systemUserSecurity.SecurityGroupID = securityGroupID;
            systemUserSecurity.AutoID = autoID;
            return systemUserSecurity;
        }
        /// <summary>
        /// There are no comments for Property CompanyID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this.OnCompanyIDChanging(value);
                this._CompanyID = value;
                this.OnCompanyIDChanged();
                this.OnPropertyChanged("CompanyID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CompanyID;
        partial void OnCompanyIDChanging(string value);
        partial void OnCompanyIDChanged();
        /// <summary>
        /// There are no comments for Property SystemUserID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SystemUserID
        {
            get
            {
                return this._SystemUserID;
            }
            set
            {
                this.OnSystemUserIDChanging(value);
                this._SystemUserID = value;
                this.OnSystemUserIDChanged();
                this.OnPropertyChanged("SystemUserID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SystemUserID;
        partial void OnSystemUserIDChanging(string value);
        partial void OnSystemUserIDChanged();
        /// <summary>
        /// There are no comments for Property SecurityGroupID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecurityGroupID
        {
            get
            {
                return this._SecurityGroupID;
            }
            set
            {
                this.OnSecurityGroupIDChanging(value);
                this._SecurityGroupID = value;
                this.OnSecurityGroupIDChanged();
                this.OnPropertyChanged("SecurityGroupID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecurityGroupID;
        partial void OnSecurityGroupIDChanging(string value);
        partial void OnSecurityGroupIDChanged();
        /// <summary>
        /// There are no comments for Property AutoID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long AutoID
        {
            get
            {
                return this._AutoID;
            }
            set
            {
                this.OnAutoIDChanging(value);
                this._AutoID = value;
                this.OnAutoIDChanged();
                this.OnPropertyChanged("AutoID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _AutoID;
        partial void OnAutoIDChanging(long value);
        partial void OnAutoIDChanged();
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Company Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this._Company = value;
                this.OnPropertyChanged("Company");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Company _Company;
        /// <summary>
        /// There are no comments for SecurityGroup in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SecurityGroup SecurityGroup
        {
            get
            {
                return this._SecurityGroup;
            }
            set
            {
                this._SecurityGroup = value;
                this.OnPropertyChanged("SecurityGroup");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SecurityGroup _SecurityGroup;
        /// <summary>
        /// There are no comments for SystemUser in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SystemUser SystemUser
        {
            get
            {
                return this._SystemUser;
            }
            set
            {
                this._SystemUser = value;
                this.OnPropertyChanged("SystemUser");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SystemUser _SystemUser;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for XERP.LogIn.DAL.LogInDAL.SystemUserType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SystemUserTypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SystemUserTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SystemUserTypeID")]
    public partial class SystemUserType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SystemUserType object.
        /// </summary>
        /// <param name="systemUserTypeID">Initial value of SystemUserTypeID.</param>
        /// <param name="autoID">Initial value of AutoID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SystemUserType CreateSystemUserType(string systemUserTypeID, long autoID)
        {
            SystemUserType systemUserType = new SystemUserType();
            systemUserType.SystemUserTypeID = systemUserTypeID;
            systemUserType.AutoID = autoID;
            return systemUserType;
        }
        /// <summary>
        /// There are no comments for Property SystemUserTypeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SystemUserTypeID
        {
            get
            {
                return this._SystemUserTypeID;
            }
            set
            {
                this.OnSystemUserTypeIDChanging(value);
                this._SystemUserTypeID = value;
                this.OnSystemUserTypeIDChanged();
                this.OnPropertyChanged("SystemUserTypeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SystemUserTypeID;
        partial void OnSystemUserTypeIDChanging(string value);
        partial void OnSystemUserTypeIDChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property AutoID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long AutoID
        {
            get
            {
                return this._AutoID;
            }
            set
            {
                this.OnAutoIDChanging(value);
                this._AutoID = value;
                this.OnAutoIDChanged();
                this.OnPropertyChanged("AutoID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _AutoID;
        partial void OnAutoIDChanging(long value);
        partial void OnAutoIDChanged();
        /// <summary>
        /// There are no comments for SystemUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SystemUser> SystemUsers
        {
            get
            {
                return this._SystemUsers;
            }
            set
            {
                this._SystemUsers = value;
                this.OnPropertyChanged("SystemUsers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SystemUser> _SystemUsers = new global::System.Data.Services.Client.DataServiceCollection<SystemUser>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for XERP.LogIn.DAL.LogInDAL.Temp in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Temps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Temp : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Temp object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Temp CreateTemp(long ID)
        {
            Temp temp = new Temp();
            temp.ID = ID;
            return temp;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Bool_1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Bool_1
        {
            get
            {
                return this._Bool_1;
            }
            set
            {
                this.OnBool_1Changing(value);
                this._Bool_1 = value;
                this.OnBool_1Changed();
                this.OnPropertyChanged("Bool_1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Bool_1;
        partial void OnBool_1Changing(global::System.Nullable<bool> value);
        partial void OnBool_1Changed();
        /// <summary>
        /// There are no comments for Property ShortChar_1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShortChar_1
        {
            get
            {
                return this._ShortChar_1;
            }
            set
            {
                this.OnShortChar_1Changing(value);
                this._ShortChar_1 = value;
                this.OnShortChar_1Changed();
                this.OnPropertyChanged("ShortChar_1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShortChar_1;
        partial void OnShortChar_1Changing(string value);
        partial void OnShortChar_1Changed();
        /// <summary>
        /// There are no comments for Property Int_1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Int_1
        {
            get
            {
                return this._Int_1;
            }
            set
            {
                this.OnInt_1Changing(value);
                this._Int_1 = value;
                this.OnInt_1Changed();
                this.OnPropertyChanged("Int_1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Int_1;
        partial void OnInt_1Changing(global::System.Nullable<int> value);
        partial void OnInt_1Changed();
        /// <summary>
        /// There are no comments for Property Decimal_1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Decimal_1
        {
            get
            {
                return this._Decimal_1;
            }
            set
            {
                this.OnDecimal_1Changing(value);
                this._Decimal_1 = value;
                this.OnDecimal_1Changed();
                this.OnPropertyChanged("Decimal_1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Decimal_1;
        partial void OnDecimal_1Changing(global::System.Nullable<decimal> value);
        partial void OnDecimal_1Changed();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for XERP.LogIn.DAL.LogInDAL.SystemUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SystemUserID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SystemUsers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SystemUserID")]
    public partial class SystemUser : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SystemUser object.
        /// </summary>
        /// <param name="systemUserID">Initial value of SystemUserID.</param>
        /// <param name="autoID">Initial value of AutoID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SystemUser CreateSystemUser(string systemUserID, long autoID)
        {
            SystemUser systemUser = new SystemUser();
            systemUser.SystemUserID = systemUserID;
            systemUser.AutoID = autoID;
            return systemUser;
        }
        /// <summary>
        /// There are no comments for Property SystemUserID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SystemUserID
        {
            get
            {
                return this._SystemUserID;
            }
            set
            {
                this.OnSystemUserIDChanging(value);
                this._SystemUserID = value;
                this.OnSystemUserIDChanged();
                this.OnPropertyChanged("SystemUserID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SystemUserID;
        partial void OnSystemUserIDChanging(string value);
        partial void OnSystemUserIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property SystemUserTypeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SystemUserTypeID
        {
            get
            {
                return this._SystemUserTypeID;
            }
            set
            {
                this.OnSystemUserTypeIDChanging(value);
                this._SystemUserTypeID = value;
                this.OnSystemUserTypeIDChanged();
                this.OnPropertyChanged("SystemUserTypeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SystemUserTypeID;
        partial void OnSystemUserTypeIDChanging(string value);
        partial void OnSystemUserTypeIDChanged();
        /// <summary>
        /// There are no comments for Property SystemUserCodeID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SystemUserCodeID
        {
            get
            {
                return this._SystemUserCodeID;
            }
            set
            {
                this.OnSystemUserCodeIDChanging(value);
                this._SystemUserCodeID = value;
                this.OnSystemUserCodeIDChanged();
                this.OnPropertyChanged("SystemUserCodeID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SystemUserCodeID;
        partial void OnSystemUserCodeIDChanging(string value);
        partial void OnSystemUserCodeIDChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Active;
        partial void OnActiveChanging(global::System.Nullable<bool> value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property EmailAddress in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this._EmailAddress = value;
                this.OnEmailAddressChanged();
                this.OnPropertyChanged("EmailAddress");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property PasswordExpired in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> PasswordExpired
        {
            get
            {
                return this._PasswordExpired;
            }
            set
            {
                this.OnPasswordExpiredChanging(value);
                this._PasswordExpired = value;
                this.OnPasswordExpiredChanged();
                this.OnPropertyChanged("PasswordExpired");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _PasswordExpired;
        partial void OnPasswordExpiredChanging(global::System.Nullable<bool> value);
        partial void OnPasswordExpiredChanged();
        /// <summary>
        /// There are no comments for Property PasswordExpiresOn in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> PasswordExpiresOn
        {
            get
            {
                return this._PasswordExpiresOn;
            }
            set
            {
                this.OnPasswordExpiresOnChanging(value);
                this._PasswordExpiresOn = value;
                this.OnPasswordExpiresOnChanged();
                this.OnPropertyChanged("PasswordExpiresOn");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _PasswordExpiresOn;
        partial void OnPasswordExpiresOnChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPasswordExpiresOnChanged();
        /// <summary>
        /// There are no comments for Property SystemManager in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> SystemManager
        {
            get
            {
                return this._SystemManager;
            }
            set
            {
                this.OnSystemManagerChanging(value);
                this._SystemManager = value;
                this.OnSystemManagerChanged();
                this.OnPropertyChanged("SystemManager");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _SystemManager;
        partial void OnSystemManagerChanging(global::System.Nullable<bool> value);
        partial void OnSystemManagerChanged();
        /// <summary>
        /// There are no comments for Property DefaultCompanyID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DefaultCompanyID
        {
            get
            {
                return this._DefaultCompanyID;
            }
            set
            {
                this.OnDefaultCompanyIDChanging(value);
                this._DefaultCompanyID = value;
                this.OnDefaultCompanyIDChanged();
                this.OnPropertyChanged("DefaultCompanyID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DefaultCompanyID;
        partial void OnDefaultCompanyIDChanging(string value);
        partial void OnDefaultCompanyIDChanged();
        /// <summary>
        /// There are no comments for Property DefaultPlantID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DefaultPlantID
        {
            get
            {
                return this._DefaultPlantID;
            }
            set
            {
                this.OnDefaultPlantIDChanging(value);
                this._DefaultPlantID = value;
                this.OnDefaultPlantIDChanged();
                this.OnPropertyChanged("DefaultPlantID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DefaultPlantID;
        partial void OnDefaultPlantIDChanging(string value);
        partial void OnDefaultPlantIDChanged();
        /// <summary>
        /// There are no comments for Property AddressID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AddressID
        {
            get
            {
                return this._AddressID;
            }
            set
            {
                this.OnAddressIDChanging(value);
                this._AddressID = value;
                this.OnAddressIDChanged();
                this.OnPropertyChanged("AddressID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AddressID;
        partial void OnAddressIDChanging(string value);
        partial void OnAddressIDChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Image
        {
            get
            {
                if ((this._Image != null))
                {
                    return ((byte[])(this._Image.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
                this.OnPropertyChanged("Image");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Image;
        partial void OnImageChanging(byte[] value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property AutoID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long AutoID
        {
            get
            {
                return this._AutoID;
            }
            set
            {
                this.OnAutoIDChanging(value);
                this._AutoID = value;
                this.OnAutoIDChanged();
                this.OnPropertyChanged("AutoID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _AutoID;
        partial void OnAutoIDChanging(long value);
        partial void OnAutoIDChanged();
        /// <summary>
        /// There are no comments for SystemUserCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SystemUserCode SystemUserCode
        {
            get
            {
                return this._SystemUserCode;
            }
            set
            {
                this._SystemUserCode = value;
                this.OnPropertyChanged("SystemUserCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SystemUserCode _SystemUserCode;
        /// <summary>
        /// There are no comments for SystemUserType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SystemUserType SystemUserType
        {
            get
            {
                return this._SystemUserType;
            }
            set
            {
                this._SystemUserType = value;
                this.OnPropertyChanged("SystemUserType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SystemUserType _SystemUserType;
        /// <summary>
        /// There are no comments for SystemUserSecurities in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity> SystemUserSecurities
        {
            get
            {
                return this._SystemUserSecurities;
            }
            set
            {
                this._SystemUserSecurities = value;
                this.OnPropertyChanged("SystemUserSecurities");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity> _SystemUserSecurities = new global::System.Data.Services.Client.DataServiceCollection<SystemUserSecurity>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
